services:

  myschool_frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: myschool_frontend

    restart: unless-stopped

    expose:
      - "80"

    networks:
      - shared-network

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/index.html"
        ]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

    mem_limit: 128m
    mem_reservation: 64m


networks:

  shared-network:
    external: true