server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    # Fallback standard et unique pour le routage Angular (gère le GET et ignore le reste)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sécurité pour éviter que les requêtes API (POST/PUT) qui échouent ne renvoient le HTML index.html
    error_page 404 /index.html;
}