server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    # IMPORTANT : Permet d'accéder en direct via le port du conteneur (ex: :4201/dauphin/)
    # Si l'URL demande /dauphin/assets/logo.png, Nginx cherche dans /usr/share/nginx/html/assets/logo.png
    location ~ ^/(dauphin|college|lycee)/(.*)$ {
        try_files /$2 /$2/ /index.html;
    }

    # Fallback standard pour le routage interne d'Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}