
export const Constants = {
  ID_ETAT_BROUILLON: 1,
  ID_ETAT_REMISE: 2,
  ID_ETAT_ENVOYE: 3,
  ID_ETAT_VALIDE: 4,

  ID_ETAT_PUBLIE: 5,
  ID_ETAT_DEPUBLIE: 6,
  ID_ETAT_PROGRAMME: 7,
  ID_ETAT_ENCOURS: 8,
  ID_ETAT_TERMINE: 9,
  ID_ETAT_REPROGRAMME: 10,
  ID_ETAT_ANNULE: 11,
  ID_ETAT_CLOTURE: 12,
  ID_ETAT_REACTIVATION: 13,
  ID_ETAT_AVENIR: 14,
  ID_ETAT_ACCEPTE: 15,
  ID_ETAT_REJETE: 16,

  ID_ETAT_PAIEMENT_PARTIEL: 17,
  ID_ETAT_A_CONFIRME: 18,
  ID_ETAT_PAIEMENT_REJETE: 19,
  ID_ETAT_PAYEE: 20
};