export const EtatCode = {
  ETAT_BROUILLON: "E1",
  ETAT_REMISE: "E2",
  ETAT_ENVOYEE: "E3",
  ETAT_VALIDEE: "E4",
  ETAT_PUBLIE: "E5",
  ETAT_DEPUBLIE: "E6",
  ETAT_PROGRAMME: "E7",
  ETAT_ENCOURS: "E8",
  ETAT_TERMINE: "E9",
  ETAT_REPROGRAMME: "E10",
  ETAT_ANNULE: "E11",
  ETAT_CLOTURE: "E12",
  ETAT_REACTIVATION: "E13",
  ETAT_AVENIR: "E14",
  ETAT_ACCEPTE: "E15",
  ETAT_REJETE: "E16",
  ETAT_PAYEE_PARTIELLE: "E17",
  ETAT_A_CONFIRMEE: "E18",
  ETAT_PAY_REJETE: "E19",
  ETAT_PAYEE: "E20",
  ETAT_EN_ATTENTE: "E21"

};