export enum TypeRelationParent {
   PARENT = 'PARENT',
  TUTEUR = 'TUTEUR',
  RESPONSABLE_LEGAL = 'RESPONSABLE_LEGAL',
  GRAND_PARENT = 'GRAND_PARENT',
  FRERE_SOEUR = 'FRERE_SOEUR',
  AUTRE = 'AUTRE'
}