export const TypeSignalement = {
  ADMIN: 'ADMINISTRATION',
  ENSEIGNANT: 'ENSEIGNANT',
  PARENT: 'PARENT',
  ELEVE: 'ELEVE'
};


export const AttendanceStatus = {
  ABSENCE: 'ABSENCE',
  RETARD: 'RETARD',
  PRESENCE: 'PRESENCE',
  EXCLUSION: 'EXCLUSION',
  JUSTIFICATION: 'JUSTIFICATION',
  MALADIE: 'MALADIE'
}

export const AttendanceSource = {
  ADMIN: 'ADMINISTRATION',
  ENSEIGNANT: 'ENSEIGNANT',
  PARENT: 'PARENT',
  SUPERVISOR: 'SUPERVISOR',
  SYSTEM: 'SYSTEM'
};
