export enum SetupStep {

  INITIATED = 'INITIATED',

  ETABLISSEMENT = 'ETABLISSEMENT',

  ANNEE_SCOLAIRE = 'ANNEE_SCOLAIRE',

  STRUCTURE_PEDAGOGIQUE = 'STRUCTURE_PEDAGOGIQUE',

  CLASSES = 'CLASSES',

  PERIODES_SCOLAIRES = 'PERIODES_SCOLAIRES',

  MATIERES = 'MATIERES',

  FINALISATION= 'FINALISATION'

}