name: CI/CD Frontend EduSchool

on:
  push:
    branches:
      - master # Déclenchement sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "====== Début de l'automatisation FRONTEND ======"

            # 1. On se positionne dans le dossier où se trouvent le code et le docker-compose
            cd ~/apps/frontend/eduschool/eduschooldauphin

            # 2. On récupère le dernier code mis à jour
            git pull origin master

            echo "====== Rebuild forcé sans cache (Anti-Cache Docker) ======"
            # 3. On force Docker à recompiler Angular en ignorant le cache pour voir les changements de code
            docker compose build --no-cache angular-dauphin
            docker compose build --no-cache angular-college

            echo "====== Relance des conteneurs à chaud ======"
            # 4. On applique la nouvelle image à chaud (Zéro Coupure)
            docker compose up -d angular-dauphin angular-college

            echo "====== Redémarrage du Proxy Global (Dossier Infra) ======"
            # CORRECTION : On se déplace dans l'infra et on relance le bon service "nginx"
            cd ~/infra
            docker compose restart nginx

            # 5. Nettoyage des anciennes images inutilisées
            docker image prune -f

            echo "====== Déploiement Frontend terminé avec succès ! ======"
